Repository asfadmin/Discovery-asf_search, pull requests merged in 2021-07, with the labels that each got.

#31 Implicit conversion to list on some search function arguments; use implicit geojson conversion in examples; generic download_urls() function with parallel support
  CHANGELOG.md
  README.md
  asf_search/download/__init__.py
  asf_search/download/download.py
  asf_search/search/search.py
Labels: minor

#28 Importlib metadata fix for python <3.8; Change "parallel"->"processes" in download handler; Implicit conversion to list on some search function arguments; use implicit geojson conversion in examples; generic download_urls() function with parallel support
  CHANGELOG.md
  README.md
  asf_search/ASFSearchResults.py
  asf_search/__init__.py
  asf_search/download/__init__.py
  asf_search/download/download.py
  asf_search/search/search.py
  setup.py
Labels: minor

#35 Fix import error; update ASFProduct/ASFSearchResults download methods to use path
  CHANGELOG.md
  asf_search/ASFProduct.py
  asf_search/ASFSearchResults.py
  asf_search/__init__.py
Labels: patch

#36 Fix versioning workflow
  .github/workflows/prod-request-merged.yml
  CHANGELOG.md
Labels: patch

#41 Add instrument constants for C-SAR, PALSAR, and AVNIR-2
  CHANGELOG.md
  asf_search/constants/INSTRUMENT.py
Labels: patch

#43 Feature auth download - Cookies, user/pass supported
  CHANGELOG.md
  README.md
  asf_search/ASFProduct.py
  asf_search/ASFSearchResults.py
  asf_search/ASFSession.py
  asf_search/__init__.py
  asf_search/constants/INTERNAL.py
  asf_search/constants/__init__.py
  asf_search/download/download.py
  asf_search/exceptions.py
  asf_search/health/health.py
  asf_search/search/baseline_search.py
  asf_search/search/geo_search.py
  asf_search/search/granule_search.py
  asf_search/search/product_search.py
  asf_search/search/search.py
Labels: major

#44 Feature: Auth download
  CHANGELOG.md
  README.md
  asf_search/ASFProduct.py
  asf_search/ASFSearchResults.py
  asf_search/ASFSession.py
  asf_search/__init__.py
  asf_search/constants/INTERNAL.py
  asf_search/constants/__init__.py
  asf_search/download/download.py
  asf_search/exceptions.py
  asf_search/health/health.py
  asf_search/search/baseline_search.py
  asf_search/search/geo_search.py
  asf_search/search/granule_search.py
  asf_search/search/product_search.py
  asf_search/search/search.py
Labels: major
